{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-docs.fullname" . }}-metrics
  labels:
    {{- include "redis-docs.labels" . | nindent 4 }}
data:
  config.hcl: |
    listen {
      port = 4040
    }

    namespace "nginx" {
      source {
        files = ["/var/log/nginx/access.log"]
      }

      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time"

      labels {
        app = "redis-docs"
      }

      histogram_buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
    }
{{- end }}
