{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "redis-docs.fullname" . }}
  labels:
    {{- include "redis-docs.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "redis-docs.fullname" . }}
    weight: 100
  port:
    targetPort: {{ if and .Values.tls.enabled .Values.tls.nginxTermination }}https{{ else }}http{{ end }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    {{- if .Values.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if and .Values.tls.enabled .Values.tls.certificate }}
    certificate: |-
{{ .Values.tls.certificate | b64dec | indent 6 }}
    key: |-
{{ .Values.tls.privateKey | b64dec | indent 6 }}
    {{- if .Values.tls.caCertificate }}
    caCertificate: |-
{{ .Values.tls.caCertificate | b64dec | indent 6 }}
    {{- end }}
    {{- end }}
    {{- if .Values.route.tls.destinationCACertificate }}
    destinationCACertificate: |
      {{ .Values.route.tls.destinationCACertificate | nindent 6 }}
    {{- end }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
