{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-docs.fullname" . }}-tls
  labels:
    {{- include "redis-docs.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ include "redis-docs.cleanPem" .Values.tls.certificate | b64enc | quote }}
  tls.key: {{ include "redis-docs.cleanPem" .Values.tls.privateKey | b64enc | quote }}
  {{- if .Values.tls.caCertificate }}
  ca.crt: {{ include "redis-docs.cleanPem" .Values.tls.caCertificate | b64enc | quote }}
  {{- end }}
{{- end }}
