{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-docs.fullname" . }}-tls
  labels:
    {{- include "redis-docs.labels" . | nindent 4 }}
{{- if or .Values.tls.certificate .Values.tls.privateKey }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | quote }}
  tls.key: {{ .Values.tls.privateKey | quote }}
  {{- if .Values.tls.caCertificate }}
  ca.crt: {{ .Values.tls.caCertificate | quote }}
  {{- end }}
{{- else if .Values.tls.pfx.data }}
type: Opaque
data:
  keystore.pfx: {{ .Values.tls.pfx.data | quote }}
  {{- if .Values.tls.pfx.password }}
  pfx-password: {{ .Values.tls.pfx.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
