apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-docs.fullname" . }}
  labels:
    {{- include "redis-docs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.tls.enabled .Values.tls.nginxTermination }}
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: 4040
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "redis-docs.selectorLabels" . | nindent 4 }}
