{{- if .Values.search.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-docs.fullname" . }}-search
  labels:
    {{- include "redis-docs.labels" . | nindent 4 }}
    app.kubernetes.io/component: search
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "redis-docs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: search
{{- end }}
